pipeline {
    agent any

    tools {
        nodejs 'Node18' 
    }

    environment {
        ALLURE_RESULTS = "${env.WORKSPACE}/SwagLabs_Practico_6/allure-results"
        ALLURE_REPORT  = "${env.WORKSPACE}/SwagLabs_Practico_6/allure-report"
    }

    stages {


        stage('Instalar dependencias') {
            steps {
                // Entramos a la carpeta del proyecto
                dir('SwagLabs_Practico_6') {
                    echo 'Instalando dependencias de Node.js...'
                    bat 'npm install' 
                }
            }
        }

        stage('Ejecutar WDIO') {
            steps {
                dir('SwagLabs_Practico_6') {
                    echo "Ejecutando pruebas WDIO..."
                    bat "npx wdio run wdio.conf.js" 
                }
            }
        }

        stage('Generar reporte Allure') {
            steps {
                dir('SwagLabs_Practico_6') {
                    echo "Generando reporte Allure..."
                    bat """
                    npx allure generate %ALLURE_RESULTS% --clean -o %ALLURE_REPORT%
                    """
                }
            }
        }

        stage('Publicar reporte Allure en Jenkins') {
            steps {
                echo "Publicando reporte Allure usando el plugin..."
                allure([
                    includeProperties: false,
                    jdk: '',
                    results: [[path: 'SwagLabs_Practico_6/allure-results']], 
                    reportBuildPolicy: 'ALWAYS'
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline finalizada'
            cleanWs() 
        }
        success {
            echo 'Pruebas WDIO ejecutadas con éxito.'
        }
    }
}